// AUTO-GENERATED by scripts/sync-system.mjs from the "H1 & H3" and
// "H2 Problem Space" tabs of the H3 Idea Database Google Sheet. Do not edit by
// hand — re-run `npm run sync-system` (or `npm run fetch-sheet && npm run sync-system`).
//
// PROBLEM_AREAS  — one per H1 & H3 row: the H1 status quo and H3 vision for a
//                  slice of the system, keyed by sheet ID.
// H2_IDEAS       — one per H2 Problem Space row: a near-term (H2−) or
//                  capacity-building (H2+) idea, linked back to the problem
//                  area(s) it addresses via h1h3Ids.

export type DomainKey = "capacity" | "staffing" | "information" | "technology" | "oversight";

// A source / "Learn more" reference. `url` is omitted for plain-text entries
// (e.g. "Interview with House staff"); when present, `title` is the link's label.
export type SourceLink = {
  title: string;
  url?: string;
};

export type ProblemArea = {
  id: string;
  domains: DomainKey[];
  bucket: string;
  h1Time: number | null;
  h1Statement: string;
  h1Description: string;
  h3Time: number | null;
  h3Statement: string;
  h3Description: string;
};

export type H2Idea = {
  id: string;
  domains: DomainKey[];
  bucket: string;
  additionalTags: string;
  horizon: "H2-" | "H2+";
  horizonKey: "h2neg" | "h2pos";
  year: number | null;
  h1h3Ids: string[];
  problemStatement: string;
  problemDescription: string;
  solutionStatement: string;
  solutionDescription: string;
  horizonJustification: string;
  pathToH2plus: string;
  currentStatus: string;
  sources: SourceLink[];
  learnMore: SourceLink[];
};

export const DOMAIN_LABELS: Record<DomainKey, string> = {
  "capacity": "Institutional Capacity",
  "staffing": "Staffing & Talent",
  "information": "Information",
  "technology": "Technology & Systems",
  "oversight": "Oversight"
};

export const PROBLEM_AREAS: ProblemArea[] = [
  {
    "id": "1a",
    "domains": [
      "staffing"
    ],
    "bucket": "personnel",
    "h1Time": 2020,
    "h1Statement": "Congress has difficulty attracting talent",
    "h1Description": "Entry-level roles run on unpaid or barely paid internships that filter for students who can afford to work for free, and starting salaries lose out to lobbying firms, agencies, and the private sector before a candidate ever applies.",
    "h3Time": 2029,
    "h3Statement": "Congress is seen as a competitive employer",
    "h3Description": "Competitive initial compensation with benefits and recruitment beyond the networks that currently supply Capitol Hill make public legislative service an attractive first job."
  },
  {
    "id": "1b",
    "domains": [
      "staffing"
    ],
    "bucket": "personnel",
    "h1Time": 2019,
    "h1Statement": "Congress underinvests in its people",
    "h1Description": "Onboarding, mentorship, and training vary office by office with no institutional floor, so a staffer's grasp of procedure, policy, and oversight depends on where they landed rather than any deliberate investment.",
    "h3Time": 2030,
    "h3Statement": "Congress invests in its workforce's expertise",
    "h3Description": "Structured onboarding, mentorship, and institution-wide HR standards give every staffer the same baseline knowledge regardless of which office hires them."
  },
  {
    "id": "1c",
    "domains": [
      "staffing"
    ],
    "bucket": "personnel",
    "h1Time": 2021,
    "h1Statement": "Congress has difficulty retaining talent",
    "h1Description": "Staff leave for lobbyists and agencies as their expertise matures, shifting the knowledge advantage to the very interests Congress is meant to scrutinize. A legislature that cannot think independently cannot govern independently.",
    "h3Time": 2031,
    "h3Statement": "Congress retains institutional knowledge",
    "h3Description": "Competitive pay, benefits, and career paths that let people build a life on the Hill turn a two-year stop into a career, keeping expertise in-house and preserving Congress's ability to execute effectively."
  }
];

export const H2_IDEAS: H2Idea[] = [
  {
    "id": "1",
    "domains": [
      "staffing"
    ],
    "bucket": "",
    "additionalTags": "Professional Development, Interns",
    "horizon": "H2+",
    "horizonKey": "h2pos",
    "year": 2028,
    "h1h3Ids": [
      "1b"
    ],
    "problemStatement": "Senate interns and intern coordinators are unsupported",
    "problemDescription": "The House Intern Resource Office (HIRO), created from a Select Committee on Modernization recommendation, is the House's central hub for internships, handling onboarding, professional development, coordinator training, and institution-wide data collection. The Senate has no equivalent, so each office builds its program in isolation. Internship quality depends entirely on where an intern lands, and the institution cannot say how many unpaid interns it hosts or offer demographic data beyond what payroll disclosures incidentally capture.",
    "solutionStatement": "Establish a Senate Intern Resource Office",
    "solutionDescription": "Fund a Senate Intern Resource Office as the chamber's counterpart to HIRO, giving interns and the staffers who manage them consistent onboarding and professional development, and maintaining records on intern numbers, pay, and demographics—work that has fallen to outside organizations by default. Use would be voluntary, preserving each Senator's authority over their own program while ensuring no office has to start from scratch. It should be Senate-specific rather than an extension of HIRO, since the chambers run on different rules and traditions.",
    "horizonJustification": "Interns are the Senate's main talent pipeline, and this strengthen the pipeline from the start.",
    "pathToH2plus": "",
    "currentStatus": "Senate Sergeant-at-Arms Karen Gibson asked the Leg Branch Approps subcommittee for funding to launch this initiative with two FTEs in FY2025. However, no funding has been dedicated to it.",
    "sources": [
      {
        "title": "appropriations.senate.gov",
        "url": "https://www.appropriations.senate.gov/imo/media/doc/download_testimony78.pdf"
      },
      {
        "title": "Interview with House staff"
      }
    ],
    "learnMore": [
      {
        "title": "popvox.org",
        "url": "https://www.popvox.org/blog/evolution"
      },
      {
        "title": "rollcall.com",
        "url": "https://rollcall.com/2024/05/29/house-intern-resource-office-ready/"
      },
      {
        "title": "everycrsreport.com",
        "url": "https://www.everycrsreport.com/files/2025-05-22_R44491_651f5c72e01c6f5aa6b8efb5822220095e1f980d.html"
      }
    ]
  }
];
